### ISSUE TITLE
ImportError: cannot import name 'tube_nms_cuda'

### ISSUE THREAD

**Issue by chenyihang1993** [Alpha-Video/AlphaVideo#4]
When I import the alphavideo, the error raise:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/data/git/alphaVideo/alphavideo/__init__.py", line 1, in <module>
    from . import model
  File "/home/data/git/alphaVideo/alphavideo/model/__init__.py", line 1, in <module>
    from .TubeTK import tubeTK
  File "/home/data/git/alphaVideo/alphavideo/model/TubeTK.py", line 1, in <module>
    from alphavideo.mot.TubeTK.TubeTK import TubeTK
  File "/home/data/git/alphaVideo/alphavideo/mot/TubeTK/TubeTK.py", line 7, in <module>
    from alphavideo.mot.TubeTK.head import TrackHead
  File "/home/data/git/alphaVideo/alphavideo/mot/TubeTK/head.py", line 8, in <module>
    from alphavideo.utils.tube_nms import multiclass_tube_nms
  File "/home/data/git/alphaVideo/alphavideo/utils/tube_nms.py", line 2, in <module>
    from alphavideo.utils import tube_nms_cuda
ImportError: cannot import name 'tube_nms_cuda'
```
I installed the alphavideo by using pip. Could you tell me how to solve it?

**Comment by CrossStyle** [comment]
I solve the problem. I installed it from source code and restarted the console.
